# Generated by Django 5.1 on 2024-08-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='checklist_type',
            field=models.CharField(choices=[('daily', 'Information Security Daily Checklist'), ('privileged', 'Privileged Account Monitoring Checklist')], max_length=255),
        ),
    ]
