# Generated by Django 5.1 on 2024-08-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_alter_checklist_checklist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='file',
            field=models.FileField(upload_to='static/checklists'),
        ),
    ]
