# Generated by Django 5.1 on 2024-08-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_alter_checklist_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='file',
            field=models.FileField(upload_to='checklists'),
        ),
    ]
