# Generated by Django 5.1 on 2024-08-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_alter_checklist_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to='static/checklists_signed'),
        ),
    ]
