# Generated by Django 5.1 on 2024-08-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_comment_signed_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='signature',
        ),
    ]
