# Generated by Django 5.1 on 2024-08-22 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_users_created_at_users_deleted_at_users_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_object_auditlogs', to='checklist.users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_auditlogs', to='checklist.users')),
            ],
        ),
    ]
