# Generated by Django 5.1 on 2024-08-23 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='logged_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklist.users'),
        ),
    ]
