# Generated by Django 5.1 on 2024-08-23 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0010_remove_auditlog_user_auditlog_logged_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='logged_user',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='target_object',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_user_auditlogs', to='checklist.users'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_user_auditlogs', to='checklist.users'),
        ),
    ]
