# Generated by Django 5.1 on 2024-08-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_remove_auditlog_logged_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_user_auditlogs', to='checklist.users'),
        ),
    ]
