# Generated by Django 5.1 on 2024-08-26 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0012_alter_auditlog_action_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_user_auditlogs', to='checklist.users'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_user_auditlogs', to='checklist.users'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_checklists', to='checklist.users'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_checklists', to='checklist.users'),
        ),
    ]
