# Generated by Django 5.1 on 2024-08-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0013_users_is_active_alter_auditlog_action_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default='True', null=True),
        ),
    ]
